---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.0"

sudo: false

script: 'STRINGIFY_FACTS=no FUTURE_PARSER=yes bundle exec rake validate && STRINGIFY_FACTS=no FUTURE_PARSER=yes bundle exec rake lint && SPEC_OPTS="--format documentation" STRINGIFY_FACTS=no FUTURE_PARSER=yes bundle exec rake spec'

matrix:
  fast_finish: true

notifications:
  email: false
